tcmu: Implement TCMU handler
Signed-off-by: Fam Zheng <famz@redhat.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3116,6 +3116,11 @@ fi
 # tcmu support probe
 
 if test "$tcmu" != "no"; then
+  # Sanity check for gio-unix-2.0 (part of glib2), cannot fail unless something
+  # is very wrong.
+  if ! $pkg_config gio-unix-2.0; then
+    error_exit "glib is required to compile QEMU"
+  fi
   cat > $TMPC <<EOF
 #include <stdio.h>
 #include <libtcmu.h>
@@ -3128,8 +3133,8 @@ int main(int argc, char **argv)
 EOF
   if compile_prog "" "-ltcmu" ; then
     tcmu=yes
-    tcmu_cflags=""
-    tcmu_libs="-ltcmu"
+    tcmu_cflags="$($pkg_config gio-unix-2.0 --cflags)"
+    tcmu_libs="-ltcmu $($pkg_config gio-unix-2.0 --libs)"
   elif test "$tcmu" == "yes"; then
     feature_not_found "libtcmu" "Install libtcmu devel"
   else
